name: Make release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Extract version
      id: extract_version
      run: printf %s '${{ github.ref }}' | sed -E 's/^.*v(.*)$/::set-output name=version::\1/'
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Set up JDK 15
      uses: actions/setup-java@v2
      with:
        java-version: '15'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: jar
        path: build/libs/sparetheanimals-${{ steps.extract_version.outputs.version }}.jar

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Extract version
      id: extract_version
      run: printf %s '${{ github.ref }}' | sed -E 's/^.*v(.*)$/::set-output name=version::\1/'
    - name: Download artifact
      uses: actions/download-artifact@v1
      with:
        name: jar
        path: .
    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ steps.extract_version.outputs.version }}
        draft: false
        prerelease: false
    - name: Upload asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./sparetheanimals-${{ steps.extract_version.outputs.version }}.jar
        asset_name: sparetheanimals-${{ steps.extract_version.outputs.version }}.jar
        asset_content_type: application/java-archive
